image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

test_script:
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации
                                                    # -Dselenide.headless=true запустит браузер в невидимом режиме
on_finish:
  - ./gradlew allureReport --clean
  - 7z a build/reports.zip build/reports/
  - appveyor PushArtifact build/reports.zip